apiVersion: v1
kind: Service
metadata:
  name: hpa-demo-service
  namespace: default
spec:
  selector:
    app: hpa-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP