apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-demo-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: keda-demo-app
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 15
  cooldownPeriod: 30
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "50"