apiVersion: v1
kind: Pod
metadata:
  name: pod-avoid-infra
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-type
            operator: NotIn
            values:
            - infra
  containers:
  - name: nginx
    image: nginx:alpine