apiVersion: v1
kind: Pod
metadata:
  name: pod-no-match
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-type
            operator: In
            values:
            - gpu
  containers:
  - name: nginx
    image: nginx:alpine