apiVersion: v1
kind: Pod
metadata:
  name: frontend-app
  labels:
    app: frontend-app
spec:
  containers:
    - name: frontend-app
      image: sarojbehera/frontend:latest   # Built from EASY_CRUD Dockerfile with updated .env
      ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: frontend-svc
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: frontend-app
  type: LoadBalancer